export const TRANSACTION_CATEGORIES = [
  "belanja",
  "hiburan",
  "kesehatan",
  "lainnya",
  "makanan",
  "pendidikan",
  "tagihan",
  "tidak_diketahui",
  "topup_ewallet",
  "transfer_internal",
  "transfer_keluarga",
  "transfer_sosial",
  "transport",
];
export const CATEGORY_MAPPING = {
  Category_0: "belanja",
  Category_1: "hiburan",
  Category_2: "kesehatan",
  Category_3: "lainnya",
  Category_4: "makanan",
  Category_5: "pendidikan",
  Category_6: "tagihan",
  Category_7: "tidak_diketahui",
  Category_8: "topup_ewallet",
  Category_9: "transfer_internal",
  Category_10: "transfer_keluarga",
  Category_11: "transfer_sosial",
  Category_12: "transport",
};
